# Generated by Django 5.2 on 2025-05-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('positionTitle', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('jobCategory', models.CharField(max_length=100)),
                ('coverLetter', models.CharField(max_length=100)),
                ('discoveryMethod', models.CharField(max_length=100)),
            ],
        ),
    ]
