# Generated by Django 5.2 on 2025-05-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='coverLetter',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='discoveryMethod',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='jobCategory',
            field=models.CharField(max_length=50),
        ),
    ]
