# Generated by Django 5.2 on 2025-05-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_application_coverletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interviewCount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='jobOffer',
            field=models.BooleanField(default=False),
        ),
    ]
